name: Actions Workflow

on:
  push:
    branches:
    # Only on these branches
      - "master"
      - "feature/*" # Matches feature/featA, feature/featureb but doesnt match,
      # feature /feat/a
      - "feature/**" #Matches /feat/a
    #branches-ignore:  We cannot use branches and branches-ignore together we need to use them separately
      #- ""
    tags:
      - v1.* # Target a tag
    paths:
      - "**.java" # Only trigger when we change a .java file
      - "!this.java" # Exclude this.java from triggering the action
  #schedule:
  #  - cron: "0/5 * * * *"
  repository_dispatch:
    types: [build]
  pull_request:
    branches:
      - "master"
    types:
      #- "closed"
      #- "assigned"
      - "opened"
      #- "reopened"

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Get Payload
        run: echo ${{ github.event.client_payload.env }}
      - name: List Files and Variables
        run: |
          pwd
          ls -la
          echo ${GITHUB_SHA}
          echo ${GITHUB_WORKSPACE}
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files after checkout
        run: |
          pwd
          ls -la
      - name: Simple JS action
        id: greet
        uses: actions/hello-world-javascript-action@v1 # Repository where the action is stored
        with:
          who-to-greet: Daniel
      - name: Log greeting time
        run: echo "${{ steps.greet.outputs.time }}" # greet = id, outputs.time is the output generated by the action
